/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chinaedustar.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * @struts.form name="forgetUserPsdForm"
 */
public class ForgetUserPsdForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = -2936593258459425264L;

	/** userId property */
	private String userId;

	/** answer property */
	private String answer;

	/** question property */
	private String question;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the userId.
	 * @return String
	 */
	public String getUserId() {
		return userId;
	}

	/** 
	 * Set the userId.
	 * @param userId The userId to set
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/** 
	 * Returns the answer.
	 * @return String
	 */
	public String getAnswer() {
		return answer;
	}

	/** 
	 * Set the answer.
	 * @param answer The answer to set
	 */
	public void setAnswer(String answer) {
		this.answer = answer;
	}

	/** 
	 * Returns the question.
	 * @return String
	 */
	public String getQuestion() {
		return question;
	}

	/** 
	 * Set the question.
	 * @param question The question to set
	 */
	public void setQuestion(String question) {
		this.question = question;
	}
}