/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.chinaedustar.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * @struts.form name="modifyPsdForm"
 */
public class ModifyPsdForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 2579418379500687928L;

	/** conPsd property */
	private String conPsd;

	/** loginId property */
	private String loginId;

	/** newPsd property */
	private String newPsd;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the conPsd.
	 * @return String
	 */
	public String getConPsd() {
		return conPsd;
	}

	/** 
	 * Set the conPsd.
	 * @param conPsd The conPsd to set
	 */
	public void setConPsd(String conPsd) {
		this.conPsd = conPsd;
	}

	/** 
	 * Returns the loginId.
	 * @return String
	 */
	public String getLoginId() {
		return loginId;
	}

	/** 
	 * Set the loginId.
	 * @param loginId The loginId to set
	 */
	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	/** 
	 * Returns the newPsd.
	 * @return String
	 */
	public String getNewPsd() {
		return newPsd;
	}

	/** 
	 * Set the newPsd.
	 * @param newPsd The newPsd to set
	 */
	public void setNewPsd(String newPsd) {
		this.newPsd = newPsd;
	}
}